import Banner from '@/components/banner/banner'
import Categories from '@/components/categories/categories'
import ChooseUs from '@/components/chooseUs/chooseUs'
import Footer from '@/components/footer/footer'
import Nav from '@/components/header/navber'
import TopHeader from '@/components/header/top-header'
import Newsletter from '@/components/newsletter/newsletter'
import Tranding from '@/components/tranding/tranding'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Alpona Jewlry</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TopHeader />
        <Banner />
        <Nav />
        <Categories />
        <ChooseUs />
        <Tranding />
        <Newsletter />
        <Footer />
      </main>
    </>
  )
}
